config/routes.rb
Rails.application.routes.draw do
  resources :missions
  resources :administrators
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
    has_many :tasks
    has_many :guests

    accepts_nested_attributes_for :guests, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
    belongs_to :administrator
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :administrator
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :administrators

    accepts_nested_attributes_for :administrators, reject_if: :all_blank, allow_destroy: true
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params.require(:administrator).permit(:nome, :matricula, :telefone, :email,
                    tasks_attributes: [:id, :descricao, :valor, :prazo, :_destroy],
                    guests_attributes: [:id, :nome, :email, :_destroy])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:show, :edit, :update, :destroy]

  # GET /missions
  # GET /missions.json
  def index
    @missions = Mission.all
  end

  # GET /missions/1
  # GET /missions/1.json
  def show
  end

  # GET /missions/new
  def new
    @mission = Mission.new
  end

  # GET /missions/1/edit
  def edit
  end

  # POST /missions
  # POST /missions.json
  def create
    @mission = Mission.new(mission_params)

    respond_to do |format|
      if @mission.save
        format.html { redirect_to @mission, notice: 'Mission was successfully created.' }
        format.json { render :show, status: :created, location: @mission }
      else
        format.html { render :new }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/1
  # PATCH/PUT /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to @mission, notice: 'Mission was successfully updated.' }
        format.json { render :show, status: :ok, location: @mission }
      else
        format.html { render :edit }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1
  # DELETE /missions/1.json
  def destroy
    @mission.destroy
    respond_to do |format|
      format.html { redirect_to missions_url, notice: 'Mission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mission_params
      params.require(:mission).permit(:status, :administrator_id, :task_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:descricao, :valor, :prazo,
                      administrators_attributes: [:id, :nome, :matricula, :telefone, :email, :_destroy])
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/administrators/_form.html.erb
<%= form_with(model: administrator, local: true) do |form| %>
  <% if administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% administrator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.text_field :matricula %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div id="guests">
    <%= form.fields_for :guests do | guests_fields | %>
      <%= render partial: "guest_fields", locals: {f: guests_fields} %>
    <% end %>

    <%= link_to_add_association('[Novo convidado]', form, :guests) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/administrators/_guest_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :nome %>
        <%= f.text_field :nome %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= link_to_remove_association('[Remover]', f) %>
    </div>
</div>

app/views/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form', administrator: @administrator %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Administrators</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Telefone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.nome %></td>
        <td><%= administrator.matricula %></td>
        <td><%= administrator.telefone %></td>
        <td><%= administrator.email %></td>
        <td><%= link_to 'Show', administrator %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_administrator_path %>

app/views/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form', administrator: @administrator %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @administrator.nome %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @administrator.matricula %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @administrator.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @administrator.email %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IChurras</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/missions/_form.html.erb
<%= form_with(model: mission, local: true) do |form| %>
  <% if mission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mission.errors.count, "error") %> prohibited this mission from being saved:</h2>

      <ul>
      <% mission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="field">
    <%= form.label :administrator_id %>
    <%= form.text_field :administrator_id %>
  </div>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.text_field :task_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/missions/edit.html.erb
<h1>Editing Mission</h1>

<%= render 'form', mission: @mission %>

<%= link_to 'Show', @mission %> |
<%= link_to 'Back', missions_path %>

app/views/missions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Missions</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Administrator</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td><%= mission.status %></td>
        <td><%= mission.administrator %></td>
        <td><%= mission.task %></td>
        <td><%= link_to 'Show', mission %></td>
        <td><%= link_to 'Edit', edit_mission_path(mission) %></td>
        <td><%= link_to 'Destroy', mission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mission', new_mission_path %>

app/views/missions/new.html.erb
<h1>New Mission</h1>

<%= render 'form', mission: @mission %>

<%= link_to 'Back', missions_path %>

app/views/missions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @mission.status %>
</p>

<p>
  <strong>Administrator:</strong>
  <%= @mission.administrator %>
</p>

<p>
  <strong>Task:</strong>
  <%= @mission.task %>
</p>

<%= link_to 'Edit', edit_mission_path(@mission) %> |
<%= link_to 'Back', missions_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="field">
    <%= form.label :prazo %>
    <%= form.number_field :prazo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :descricao %>
        <%= f.text_field :descricao %>

        <%= f.label :valor %>
        <%= f.text_field :valor %>

        <%= f.label :prazo %>
        <%= f.text_field :prazo %>

        <%= link_to_remove_association('[Remover]', f) %>
    </div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Valor</th>
      <th>Prazo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.descricao %></td>
        <td><%= task.valor %></td>
        <td><%= task.prazo %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @task.descricao %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @task.valor %>
</p>

<p>
  <strong>Prazo:</strong>
  <%= @task.prazo %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>